#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo "Holberton School" >> /var/www/html/index.html

sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx start
