#!/usr/bin/env bash
# configures HAproxy as load balancer

apt-get -y update
apt-get -y install haproxy=1.6.\*

echo '
frontend kennynku.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 268362-web-01 35.168.2.196:80
        server 268362-web-02 34.224.94.141:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
